---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-modsec
data:
  allow-snippet-annotations: "true"
  enable-modsecurity: "true"
  enable-owasp-modsecurity-crs: "true"
  modsecurity-snippet: |-
    SecRuleEngine On
