apiVersion: batch/v1
kind: Job
metadata:
  name: curl-nginx-job
spec:
  template:
    spec:
      containers:
      - name: curl-nginx
        image: radial/busyboxplus:curl
        command:
        - sh
        - -c
        - |
          curl http://10.108.51.122:80
      restartPolicy: Never
  backoffLimit: 4
