apiVersion: batch/v1
kind: Job
metadata:
  name: curl-nginx-nodeport
spec:
  template:
    spec:
      containers:
      - name: curl-nginx-nodeport
        image: radial/busyboxplus:curl
        command:
        - sh
        - -c
        - |
          curl http://10.156.0.25:30080
      restartPolicy: Never
  backoffLimit: 4
