apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myserviceb-react
spec:
  rules:
  - host: andrukhiv.hopto.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service-react
            port:
              number: 8080
  ingressClassName: nginx