---
- name: Password policy hardening with PAM
  hosts: all
  become: true
  
  tasks:

  - name: Install pam_cracklib package
    apt:
      name: libpam-cracklib
      state: present

                              
  - name: Create a new file in /etc/pam.d/
    file:
      path: /etc/pam.d/common-password
      state: touch
                      
  - name: Add rule to check for user name in password
    lineinfile:
      path: /etc/pam.d/common-password
      regexp: 'password.*requisite.*pam_cracklib.so.*'
      line: 'password requisite pam_cracklib.so try_first_pass retry=3 minlen=8 usercheck = 1 enforce_for_root reject_username'
      state: present

                                                                                                                
