apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env  : prod
    owner: Andriy Andrukhiv
spec:
  selector:
    project: {{ .Release.Name }}    
  ports:
    - name      : {{ .Release.Name }}-listener
      protocol  : TCP
      port      : 80  
      targetPort: 80 
